[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
shuttle-service = { version = "0.4.2", features = ["web-tower"] }
tower = { version = "0.4", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
