[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-service = { version = "0.3.1", features = ["web-tower"] }
tower = { version = "0.4", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
