[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
description = "Shuttle test project"
license = "Apache 2.0"
homepage = "https://www.shuttle.rs/"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
rocket = "0.5.0-rc.1"
shuttle-service = "0.2.4"
