[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rocket = "0.5.0-rc.2"
shuttle-service = { version = "0.7.0", features = ["web-rocket"] }
