[package]
name = "shuttle-aws-rds"
version = "0.34.1"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to provision AWS RDS resources"
keywords = ["shuttle-service", "rds"]

[dependencies]
async-trait = "0.1.56"
paste = "1.0.7"
serde = { version = "1.0.148", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.34.1", default-features = false }
sqlx = "0.7.1"

[features]
postgres = ["sqlx/postgres", "sqlx/runtime-tokio-native-tls"]
postgres-rustls = ["sqlx/postgres", "sqlx/runtime-tokio-rustls"]
mysql = ["sqlx/mysql", "sqlx/runtime-tokio-native-tls"]
mysql-rustls = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
mariadb = ["sqlx/mysql", "sqlx/runtime-tokio-native-tls"]
mariadb-rustls = ["sqlx/mysql", "sqlx/runtime-tokio-rustls"]
