[package]
name = "shuttle-aws-rds"
version = "0.24.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to provision AWS RDS resources"
keywords = ["shuttle-service", "rds"]

[dependencies]
async-trait = "0.1.56"
paste = "1.0.7"
serde = { version = "1.0.148", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.24.0" }
sqlx = { version = "0.7.1", features = ["runtime-tokio-native-tls"] }

[features]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
mariadb = ["sqlx/mysql"]
