[package]
name = "shuttle-aws-rds"
version = "0.36.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to provision AWS RDS resources"
keywords = ["shuttle-service", "rds"]

[dependencies]
async-trait = "0.1.56"
paste = "1.0.7"
serde = { version = "1.0.148", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.36.0", default-features = false }
sqlx = { version = "0.7.1", optional = true }

[features]
default = []

# Database and TLS
postgres = ["sqlx?/postgres", "sqlx?/runtime-tokio", "sqlx?/tls-native-tls"]
postgres-rustls = ["sqlx?/postgres", "sqlx?/runtime-tokio", "sqlx?/tls-rustls"]
mysql = ["sqlx?/mysql", "sqlx?/runtime-tokio", "sqlx?/tls-native-tls"]
mysql-rustls = ["sqlx?/mysql", "sqlx?/runtime-tokio", "sqlx?/tls-rustls"]
mariadb = ["sqlx?/mysql", "sqlx?/runtime-tokio", "sqlx?/tls-native-tls"]
mariadb-rustls = ["sqlx?/mysql", "sqlx?/runtime-tokio", "sqlx?/tls-rustls"]

# Add an sqlx Pool as a resource output type
sqlx = ["dep:sqlx"]
