[workspace]
members = [
  "api",
  "cargo-shuttle",
  "codegen",
  "common",
  "proto",
  "provisioner",
  "service"
]
exclude = [
  "e2e",
  "examples",
  "services/aws-rds",
  "services/secrets",
  "services/shared-db"
]
