[workspace]
members = [
  "admin",
  "cargo-shuttle",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "proto",
  "provisioner",
  "service"
]

exclude = [
  "e2e",
  "examples",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db",
  "resources/static-folder"
]

[workspace.package]
# TODO: should we have the same version for all crates?
# version = "0.7.2"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
shuttle-common = { path = "common", version = "0.7.3" }
shuttle-proto = { path = "proto", version = "0.7.3" }
shuttle-service = { path = "service", version = "0.7.2" }
shuttle-codegen = { path = "codegen", version = "0.7.2" }

anyhow = "1.0.66"
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
once_cell = "1.16.0"
