[workspace]
members = [
  "admin",
  "cargo-shuttle",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "proto",
  "provisioner",
  "service"
]

exclude = [
  "e2e",
  "examples",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db",
  "resources/static-folder"
]

[workspace.package]
# TODO: should we have the same version for all crates?
# version = "0.7.2"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
# TODO: these are a different versions, and setting their version here can't 
# be done without them using the worspace version. Using the workspace version 
# means the resources can't resolve their dependency on shuttle-service. Look at
# other repos that have implemented inheritance to figure out a solution for this.
shuttle-common = { path = "common" }
shuttle-proto = { path = "proto" }
shuttle-service = { path = "service" }
shuttle-codegen = { path = "codegen" }

anyhow = "1.0.66"
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
once_cell = "1.16.0"
