[workspace]
members = [
  "admin",
  "cargo-shuttle",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "proto",
  "provisioner",
  "service"
]

exclude = [
  "e2e",
  "examples",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db",
  "resources/static-folder"
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"

# TODO: add local crates to the workspace dependencies when it's
# supported by cargo-chef: https://github.com/LukeMathWalker/cargo-chef/issues/167

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
axum = "0.6.0"
chrono = "0.4.23"
once_cell = "1.16.0"
uuid = "1.2.2"
thiserror = "1.0.37"
serde = "1.0.148"
serde_json = "1.0.89"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
