version: "3"

services:
  backend:
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/lib/shuttle/crates

        cat<<EOF > /var/lib/shuttle/users.toml
        [test-key]
        name = "tester"
        projects = []
        EOF

        mkdir -p $$CARGO_HOME
        cat<<EOF > $$CARGO_HOME/config.toml
        [patch.crates-io]
        shuttle-service = { path = "/usr/src/shuttle/service" }
        EOF

        exec /usr/local/bin/service "$${@:0}"
    volumes:
      - .:/usr/src/shuttle

    build:
      context: .
      dockerfile: Containerfile
      args:
        crate: shuttle-api
    image: "${CONTAINER_REGISTRY}/backend:dev"

  provisioner:
    build:
      context: .
      dockerfile: Containerfile
      args:
        crate: shuttle-provisioner
    image: "${CONTAINER_REGISTRY}/provisioner:dev"
