version: "3"
volumes:
  logger-postgres-vol:

services:
  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        until </dev/tcp/mongodb/27017
        do
          >&2 echo "mongoDB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting provisioner"

        exec /usr/local/bin/service "$${@:0}"
    ports:
      - 3000:8000
  logger:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/logger-postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting shuttle-logger"

        exec /usr/local/bin/service "$${@:0}"
  resource-recorder:
    ports:
      - 6000:8000
  logger-postgres:
    image: "${CONTAINER_REGISTRY}/logger-postgres:${LOGGER_POSTGRES_TAG}"
    restart: always
    networks:
      user-net:
    volumes:
      - logger-postgres-vol:/var/lib/postgresql/data
    ports:
      - 8002:8000
      - 5432:5432
  panamax:
    profiles:
      - panamax
  deck-chores:
    profiles:
      - panamax
