version: "3"

services:
  auth:
    ports:
      - 8008:8000
  builder:
    ports:
      - 8010:8000
    command:
      - "--auth-uri=http://host.docker.internal:8008"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  deployer:
    ports:
      - 8009:8000
    command:
      - "--auth-uri=http://host.docker.internal:8008"
      - "--state=/var/lib"
      - "--provisioner-uri=http://host.docker.internal:3000"
      - "--prefix=${STACK}"
      - "--users-network-name=${STACK}_user-net"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  gateway:
    ports:
      - 7999:7999
      - 8000:8000
      - 8001:8001
    command:
      - "--state=/var/lib"
      - "--auth-uri=http://host.docker.internal:8008"
      - "--proxy-fqdn=shuttle.local"
      - "--use-tls=disable"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  logger:
    ports:
      - 8020:8000
    command:
      - "--auth-uri=http://host.docker.internal:8008"
      - "--state=/var/lib"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        until </dev/tcp/mongodb/27017
        do
          >&2 echo "mongoDB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting provisioner"

        exec /usr/local/bin/service "$${@:0}"
    ports:
      - 3000:8000
    command:
      - "--ip=0.0.0.0"
      - "--port=8000"
      - "--shared-pg-uri=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
      - "--shared-mongodb-uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin"
      - "--internal-mongodb-address=mongodb"
      - "--internal-pg-address=postgres"
      - "--fqdn=127.0.0.1"
      - "--auth-uri=http://host.docker.internal:8008"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  resource-recorder:
    ports:
      - 8012:8000
    command:
      - "--auth-uri=http://host.docker.internal:8008"
      - "--state=/var/lib"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  deck-chores:
    profiles:
      - panamax
  panamax:
    profiles:
      - panamax
