version: "3"

volumes:
  logger-postgres-vol:


services:
  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        until </dev/tcp/mongodb/27017
        do
          >&2 echo "mongoDB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting provisioner"

        exec /usr/local/bin/service "$${@:0}"
    ports:
      - 3000:8000
  resource-recorder:
    ports:
      - 8007:8000
  otel-collector:
    ports:
      - 4317:4317
  panamax:
    profiles:
      - panamax
  deck-chores:
    profiles:
      - panamax
  logger:
    ports:
      - 8080:8000
    depends_on:
      - auth
      - logger-postgres
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/logger-postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting shuttle-logger"

        exec /usr/local/bin/service "$${@:0}"
  logger-postgres:
    image: "docker.io/library/postgres:${LOGGER_POSTGRES_TAG}"
    restart: always
    networks:
      user-net:
    environment:
      POSTGRES_PASSWORD: ${LOGGER_POSTGRES_PASSWORD}
    volumes:
      - logger-postgres-vol:/var/lib/postgresql/data
    ports:
      - 8003:8000
      # the shared postgres already uses 5432
      - 5433:5432
