version: "3"

volumes:
  logger-postgres-vol:
  control-db-postgres-vol:

services:
  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        until </dev/tcp/mongodb/27017
        do
          >&2 echo "mongoDB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting provisioner"

        exec /usr/local/bin/shuttle-provisioner "$${@:0}"
    ports:
      - 3000:8000
  resource-recorder:
    ports:
      - 8007:8000
    depends_on:
      - control-db
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/control-db/5432
        do
          >&2 echo "The control DB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "The control DB is available - starting shuttle-resource-recorder"

        exec /usr/local/bin/shuttle-resource-recorder "$${@:0}"
  auth:
    depends_on:
      - control-db
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/control-db/5432
        do
          >&2 echo "The control DB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "The control DB is available - starting shuttle-auth"

        exec /usr/local/bin/shuttle-auth "$${@:0}"
    command:
      - "--db-connection-uri=${CONTROL_DB_POSTGRES_URI}"
      - "start"
      - "--address=0.0.0.0:8000"
      - "--stripe-secret-key=${STRIPE_SECRET_KEY}"
      # used only for local development
      - "--jwt-signing-private-key=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUR5V0ZFYzhKYm05NnA0ZGNLTEwvQWNvVUVsbUF0MVVKSTU4WTc4d1FpWk4KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo="
      - "--permit-api-uri=https://api.eu-central-1.permit.io"
      - "--permit-pdp-uri=http://permit-pdp:7000"
      - "--permit-env=${SHUTTLE_ENV}"
      - "--permit-api-key=${PERMIT_DEV_API_KEY}"
  gateway:
    command:
      - "--state=/var/lib/shuttle"
      - "start"
      - "--control=0.0.0.0:8001"
      - "--user=0.0.0.0:8000"
      - "--bouncer=0.0.0.0:7999"
      - "--image=${CONTAINER_REGISTRY}/deployer:${DEPLOYER_TAG}"
      - "--prefix=shuttle_"
      - "--network-name=${STACK}_user-net"
      - "--docker-host=/var/run/docker.sock"
      - "--auth-uri=http://auth:8000"
      - "--deploys-api-key=${DEPLOYS_API_KEY}"
      - "--provisioner-host=provisioner"
      - "--proxy-fqdn=${APPS_FQDN}"
      - "--use-tls=${USE_TLS}"
      - "--cors-origin=http://localhost:3001"
      - "--admin-key=${GATEWAY_ADMIN_KEY}"
      - "--permit-api-uri=https://api.eu-central-1.permit.io"
      - "--permit-pdp-uri=http://permit-pdp:7000"
      - "--permit-env=${SHUTTLE_ENV}"
      - "--permit-api-key=${PERMIT_DEV_API_KEY}"
  otel-collector:
    ports:
      - 4317:4317
  logger:
    ports:
      - 8010:8000
    depends_on:
      - auth
      - logger-postgres
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/logger-postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting shuttle-logger"

        exec /usr/local/bin/shuttle-logger "$${@:0}"
  logger-postgres:
    image: "docker.io/library/postgres:${LOGGER_POSTGRES_TAG}"
    restart: always
    networks:
      user-net:
    environment:
      POSTGRES_PASSWORD: ${LOGGER_POSTGRES_PASSWORD}
    volumes:
      - logger-postgres-vol:/var/lib/postgresql/data
    ports:
      - 8003:8000
      # the shared postgres already uses 5432
      - 5433:5432
  control-db:
    image: "docker.io/library/postgres:${CONTROL_DB_POSTGRES_TAG}"
    restart: always
    networks:
      user-net:
    environment:
      POSTGRES_PASSWORD: ${CONTROL_DB_POSTGRES_PASSWORD}
    volumes:
      - control-db-postgres-vol:/var/lib/postgresql/data
    ports:
      - 8004:8000
      # the shared postgres already uses 5432
      - 5434:5432
  permit-pdp:
    environment:
      - PDP_DEBUG=True
      - PDP_API_KEY=${PERMIT_DEV_API_KEY}
