version: "3"
volumes:
  shuttle-backend-vol:
    external: true
services:
  api:
    image: "${CONTAINER_REGISTRY}/api:${BACKEND_TAG}"
    volumes:
      - shuttle-backend-vol:/var/lib/shuttle/
    depends_on:
      - provisioner
    ports:
      - 8000:8000
      - 8001:8001
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - SHUTTLE_USERS_TOML=/var/lib/shuttle/users.toml
      - RUST_LOG=${RUST_LOG}
    command:
      - "--path=/var/lib/shuttle/crates"
      - "--bind-addr=0.0.0.0"
      - "--api-port=8001"
      - "--proxy-port=8000"
      - "--proxy-fqdn=${APPS_FQDN}"
      - "--provisioner-address=provisioner"
      - "--provisioner-port=8000"
  provisioner:
    image: "${CONTAINER_REGISTRY}/provisioner:${PROVISIONER_TAG}"
    depends_on:
      - pg
      - mongodb
    environment:
      - RUST_LOG=${RUST_LOG}
    command:
      - "--ip=0.0.0.0"
      - "--port=8000"
      - "--shared-pg-uri=postgres://postgres:${POSTGRES_PASSWORD}@pg:5432/postgres"
      - "--shared-mongodb-uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin"
      - "--internal-mongodb-address=mongodb"
      - "--internal-pg-address=pg"
      - "--fqdn=${DB_FQDN}"
  pg:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  mongodb:
    image: mongo:5.0.10
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
