[package]
name = "shuttle-salvo"
version = "0.12.0-rc1"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a salvo webserver on shuttle"
keywords = ["shuttle-service", "salvo"]

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = { version = "0.37.5" }
shuttle-runtime = { path = "../../runtime", version = "0.12.0-rc1" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
