[package]
name = "shuttle-salvo"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a salvo webserver on shuttle"
keywords = ["shuttle-service", "salvo"]

[dependencies]
salvo = "0.41.0"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
