[package]
name = "shuttle-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-datadog = { workspace = true }
opentelemetry-http = { workspace = true }
tokio = { version = "1.22.0", features = [ "full" ] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
