[package]
name = "shuttle-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
jsonwebtoken = { workspace = true }
opentelemetry = { workspace = true }
rand = { workspace = true }
ring = { workspace = true }
sqlx = { workspace = true, features = [
    "sqlite",
    "json",
    "runtime-tokio-native-tls",
    "migrate",
] }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "models", "persist"]

[dependencies.shuttle-proto]
workspace = true

[dev-dependencies]
portpicker = { workspace = true }
pretty_assertions = { workspace = true }
