[package]
name = "cargo-shuttle"
version = "0.29.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A cargo command for the shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bollard = { workspace = true }
cargo_metadata = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env"] }
clap_complete = "4.3.1"
crossbeam-channel = { workspace = true }
crossterm = { workspace = true }
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
dirs = { workspace = true }
dunce = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
globset = "0.4.13"
home = { workspace = true }
headers = { workspace = true }
indicatif = "0.17.3"
ignore = "0.4.20"
indoc = "2.0.1"
percent-encoding = { workspace = true }
portpicker = { workspace = true }
regex = "1.9.5"
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = "0.2.0"
reqwest-retry = "0.3.0"
rmp-serde = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "signal", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.20.1", features = [
  "rustls-tls-webpki-roots",
] }
toml = { workspace = true }
toml_edit = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = [
  "default",
  "env-filter",
  "fmt",
] }
url = "2.3.1"
uuid = { workspace = true, features = ["v4"] }
walkdir = "2.3.3"
webbrowser = "0.8.2"

[dependencies.gix]
version = "0.54"
default-features = false
features = [ "blocking-http-transport-reqwest-rust-tls", "worktree-mutation" ]

[dependencies.git2]
version = "0.17.2"
default-features = false

[dependencies.shuttle-common]
workspace = true
features = ["models"]

[dependencies.shuttle-proto]
workspace = true

[dependencies.shuttle-service]
workspace = true
features = ["builder"]

[dev-dependencies]
assert_cmd = "2.0.6"
rexpect = "0.5.0"
# Tmp until this branch is merged and released
tokiotest-httpserver = { git = "https://github.com/shuttle-hq/tokiotest-httpserver", branch = "feat/body" }
shuttle-common-tests = { path = "../common-tests" }
