[package]
name = "cargo-shuttle"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
description = "A cargo command for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
bollard = "0.12.0"
chrono = "0.4.19"
colored = "2.0.0"
crossterm = "0.23.2"
dirs = "4.0.0"
env_logger = "0.9.0"
log = "0.4.17"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
toml_edit = "0.14.4"
reqwest = { version = "0.11.10", features = ["json"] }
reqwest-middleware = "0.1.6"
reqwest-retry = "0.1.5"
cargo = "0.62.0"
cargo-edit = { version = "0.9.1", features = ["cli"] }
tokio = "1.19.2"
futures = "0.3.21"
toml = "0.5.9"
structopt = "0.3.26"
cargo_metadata = "0.14.2"
webbrowser = "0.7.1"
uuid = { version = "1.1.1", features = ["v4"] }
portpicker = "0.1.1"
semver = "1.0.9"

shuttle-common = { version = "0.3.0", path = "../common" }
shuttle-service = { version = "0.3.0", path = "../service", features = [ "loader" ] }

[dev-dependencies]
test-context = "0.1.3"
# Tmp until this branch is merged and released
tokiotest-httpserver = { git = "https://github.com/shuttle-hq/tokiotest-httpserver", branch = "feat/body" }
