[package]
name = "cargo-shuttle"
version = "0.12.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A cargo command for the shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bollard = "0.13.0"
cargo = { workspace = true }
cargo-edit = { version = "0.11.9", features = ["cli"] }
cargo_metadata = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env"] }
clap_complete = "4.1.5"
crossbeam-channel = { workspace = true }
crossterm = { workspace = true }
dialoguer = { version = "0.10.3", features = ["fuzzy-select"] }
dirs = { workspace = true }
dunce = "1.0.3"
flate2 = { workspace = true }
futures = { workspace = true }
# This needs to be 0.16.0 for its dependency on libgit2-sys to be compatible
# with cargo 0.69.0's dependency on libgit2-sys.
git2 = "0.16.0"
home = { workspace = true }
headers = { workspace = true }
indicatif = "0.17.3"
ignore = "0.4.20"
indoc = "2.0.1"
openssl = { version = "0.10", optional = true }
portpicker = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = "0.2.0"
reqwest-retry = "0.2.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-native-tls", "postgres"] }
strum = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
toml = { workspace = true }
toml_edit = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = [
  "default",
  "env-filter",
  "fmt",
] }
url = "2.3.1"
uuid = { workspace = true, features = ["v4"] }
webbrowser = "0.8.2"

[dependencies.shuttle-common]
workspace = true
features = ["models"]

[dependencies.shuttle-proto]
workspace = true

[dependencies.shuttle-secrets]
version = "0.12.0"
path = "../resources/secrets"

[dependencies.shuttle-service]
workspace = true
features = ["builder"]

[features]
vendored-openssl = ["openssl/vendored"]

[dev-dependencies]
assert_cmd = "2.0.6"
rexpect = "0.5.0"
tempfile = { workspace = true }
test-context = "0.1.4"
# Tmp until this branch is merged and released
tokiotest-httpserver = { git = "https://github.com/shuttle-hq/tokiotest-httpserver", branch = "feat/body" }
