[package]
name = "shuttle-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rocket"

[[bin]]
name = "shuttle-next"
required-features = ["next"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap ={ version = "4.0.18", features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
uuid = { workspace = true, features = ["v4"] }

# TODO: bump these crates to 6.0 when we bump rust to >= 1.66
cap-std = { version = "1.0.2", optional = true }
futures = { version = "0.3.25", optional = true }
hyper = { version = "0.14.23", optional = true }
rmp-serde = { version = "1.1.1", optional = true }
wasi-common = { version = "4.0.0", optional = true }
wasmtime = { version = "4.0.0", optional = true }
wasmtime-wasi = { version = "4.0.0", optional = true }

# For rocket.rs
# TODO: remove
shuttle-secrets = { path = "../resources/secrets" }
rocket = "0.5.0-rc.2"

[dependencies.shuttle-common]
workspace = true
features = ["service"]

[dependencies.shuttle-proto]
workspace = true

[dependencies.shuttle-service]
workspace = true
features = ["builder", "web-rocket"] # TODO: remove web-rocket

[dev-dependencies]
crossbeam-channel = "0.5.6"
portpicker = "0.1.1"
futures = { version = "0.3.25" }

[features]
next = [
    "cap-std", 
    "futures", 
    "hyper/server", 
    "rmp-serde", 
    "futures", 
    "wasi-common", 
    "wasmtime", 
    "wasmtime-wasi",
    "shuttle-common/wasm"
]
