[package]
name = "shuttle-runtime"
version = "0.12.0-rc1"
edition.workspace = true
license.workspace = true
description = "Runtime to start and manage any service that runs on shuttle"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "shuttle-next"
required-features = ["next"]

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
prost-types = { workspace = true }
serde_json = { workspace = true }
strfmt = "0.2.2"
thiserror = { workspace = true }
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = ["default", "env-filter", "fmt"] }

# TODO: bump these crates to 6.0 when we bump rust to >= 1.66
cap-std = { version = "1.0.2", optional = true }
futures = { version = "0.3.25", optional = true }
hyper = { version = "0.14.23", optional = true }
rmp-serde = { version = "1.1.1", optional = true }
wasi-common = { version = "4.0.0", optional = true }
wasmtime = { version = "4.0.0", optional = true }
wasmtime-wasi = { version = "4.0.0", optional = true }

[dependencies.shuttle-common]
workspace = true
features = ["claims", "backend"]

[dependencies.shuttle-proto]
workspace = true

[dependencies.shuttle-service]
workspace = true

[dev-dependencies]
crossbeam-channel = "0.5.6"
portpicker = "0.1.1"
futures = { version = "0.3.25" }
shuttle-service = { workspace = true, features = ["builder"] }

[features]
default = []
next = [
    "cap-std", 
    "futures", 
    "hyper/server", 
    "rmp-serde", 
    "futures", 
    "wasi-common", 
    "wasmtime", 
    "wasmtime-wasi",
    "shuttle-common/wasm"
]
