[package]
name = "shuttle-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
cap-std = "1.0.2"
clap ={ version = "4.0.18", features = ["derive"] }
hyper = { version = "0.14.23", features = ["server"] }
rmp-serde = { version = "1.1.1" }
thiserror = { workspace = true }
tokio = { version = "=1.22.0", features = ["full"] }
tokio-stream = "0.1.11"
tonic = "0.8.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4"] }
wasi-common = "4.0.0"
wasmtime = "4.0.0"
wasmtime-wasi = "4.0.0"
futures = "0.3.25"

[dependencies.shuttle-common]
workspace = true
features = ["axum-wasm"]

[dependencies.shuttle-proto]
workspace = true

[dependencies.shuttle-service]
workspace = true
features = ["loader"]
