[package]
name = "shuttle-actix-web"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run an actix webserver on shuttle"
keywords = ["shuttle-service", "actix"]

[dependencies]
actix-web = "4.3.1"
num_cpus = "1.15.0"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
