[package]
name = "shuttle-secrets"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
lazy_static = "1.4.0"
regex = "1.5.6"
shuttle-service = { path = "../../service", default-features = false }
sqlx = { version = "0.5.13", features = ["runtime-tokio-native-tls", "postgres"] }
