version: 2.1

orbs: 
  docker-buildx: sensu/docker-buildx@1.1.1
  aws-ecr: circleci/aws-ecr@8.1.2
  win: circleci/windows@5.0

executors:
  docker-rust:
    docker:
      - image: cimg/rust:1.65.0
  image-ubuntu:
    machine:
      image: ubuntu-2204:2022.04.1
      docker_layer_caching: true

# sscache steps are from this guide
# https://medium.com/@edouard.oger/rust-caching-on-circleci-using-sccache-c996344f0115
commands:
  restore-cargo-cache:
    steps:
      # Restore cargo cache before installing anything with the cargo command (ie cargo install ...)
      - restore_cache:
          name: Restore cargo cache
          keys:
            - cargo-{{ checksum "Cargo.lock" }}
      - run:
          name: Install sccache
          command: |
            ls ~/.cargo/bin/sccache || cargo install sccache
            # This configures Rust to use sccache.
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            sccache --version
      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-{{ .Environment.CIRCLE_JOB }}
  save-cargo-cache:
    steps:
      - run:
          name: Sccache stats
          command: sccache --show-stats
      - save_cache:
          name: Save sccache cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: sccache-cache-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"
      - save_cache:
          name: Save cargo cache
          key: cargo-{{ checksum "Cargo.lock" }}-{{ epoch }}
          paths:
            - ~/.cargo
  restore-buildx-cache:
    steps:
      - docker-buildx/install:
          version: 0.8.2
          qemu-user-static-version: 7.0.0-7
      - restore_cache:
          name: Restore buildx cache
          keys:
            # Try lock cache first
            - docker-buildx-{{ checksum "./Cargo.lock" }}
            # Try branch cache next
            - docker-buildx-{{ .Branch }}
            # Fallback to main cache
            - docker-buildx-main
      - run:
          name: Configure buildx cache
          command: export BUILDX_CACHE=/tmp/cache/buildx
  save-buildx-cache:
    steps:
      - save_cache:
          name: Save buildx cache
          paths:
            - "/tmp/cache/buildx"
          key: docker-buildx-{{ checksum "./Cargo.lock" }}-{{ epoch }}
          when: always
  apply-patches:
    steps:
      - run:
          name: Patch service
          command: |
            cat\<< EOF > ~/.cargo/config.toml
            [patch.crates-io]
            shuttle-service = { path = "$PWD/service" }
            shuttle-aws-rds = { path = "$PWD/resources/aws-rds" }
            shuttle-persist = { path = "$PWD/resources/persist" }
            shuttle-shared-db = { path = "$PWD/resources/shared-db" }
            shuttle-secrets = { path = "$PWD/resources/secrets" }
            shuttle-static-folder = { path = "$PWD/resources/static-folder" }
            EOF
  install-rust:
    steps:
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            sudo apt update && sudo apt install -y libssl1.1
  install-protoc:
    steps:
      - run:
          name: Install protoc
          command: |
            curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-linux-x86_64.zip &&\
              sudo unzip -o protoc-21.9-linux-x86_64.zip -d /usr bin/protoc &&\
              sudo unzip -o protoc-21.9-linux-x86_64.zip -d /usr/ 'include/*' &&\
              rm -f protoc-21.9-linux-x86_64.zip
  make-artifact:
    parameters:
      target:
        description: "Rust target to put in artifact"
        type: string
      suffix:
        description: "Suffix that is on the binary"
        type: string
        default: ""
    steps:
      - run:
          name: Set git tag in the environment"
          command: |
            echo TAG=$(git describe --tags) >> $BASH_ENV
      - run:
          name: Make artifact
          command: |
            mkdir shuttle
            mv target/<< parameters.target >>/release/cargo-shuttle<< parameters.suffix >> shuttle/cargo-shuttle<< parameters.suffix >>
            mv LICENSE shuttle/
            mv README.md shuttle/
            mkdir -p artifacts/<< parameters.target >>
            cp $BASH_ENV artifacts/bash.env
            tar -cvzf artifacts/<< parameters.target >>/cargo-shuttle-$TAG-<< parameters.target >>.tar.gz shuttle
      # Persist the bash environment to the workspace as well, we need it for the release job.
      # https://discuss.circleci.com/t/share-environment-variable-between-different-job/45647/4
      - persist_to_workspace:
          root: artifacts
          paths:
            - << parameters.target >>/*
            - bash.env

jobs:
  workspace-fmt:
    executor: docker-rust
    steps:
      - checkout
      - restore-cargo-cache
      - install-protoc
      - run: cargo fmt --all --check
      - run: cargo install cargo-sort
      # TODO: this is incompatible with workspace inheritance, uncomment when 
      # https://github.com/DevinR528/cargo-sort/pull/29 is merged
      # - run: cargo sort --check --workspace
      - run: cargo check --workspace --all-targets
      - save-cargo-cache
  workspace-clippy:
    parameters:
      framework:
        description: "Framework to activate"
        type: string
    executor: docker-rust
    steps:
      - checkout
      - restore-cargo-cache
      - install-protoc
      - run: |
          cargo clippy --tests \
                       --all-targets \
                       --features="codegen,loader,<< parameters.framework >>" \
                       --no-deps -- \
                       --D warnings \
                       -A clippy::let-unit-value \
                       -A clippy::format-push-string
      - save-cargo-cache
  check-standalone:
    parameters:
      path:
        description: "Path to crate external from workspace"
        type: string
    executor: docker-rust
    steps:
      - checkout
      - restore-cargo-cache
      - install-protoc
      - apply-patches
      - run: cargo fmt --all --check --manifest-path << parameters.path >>/Cargo.toml
      - run: cargo install cargo-sort
      # TODO: this is incompatible with workspace inheritance, uncomment when 
      # https://github.com/DevinR528/cargo-sort/pull/29 is merged
      # - run: cargo sort --check << parameters.path >>
      - run: |
          cargo clippy --tests \
                       --all-targets \
                       --all-features \
                       --manifest-path << parameters.path >>/Cargo.toml \
                       --no-deps -- \
                       --D warnings \
                       -A clippy::let-unit-value \
                       -A clippy::format-push-string
      - run: cargo test --all-features --manifest-path << parameters.path >>/Cargo.toml -- --nocapture
      - save-cargo-cache
  service-test:
    # Using an image since tests will start a docker container
    executor: image-ubuntu
    steps:
      - install-rust
      - checkout
      - restore-cargo-cache
      - run:
          name: Run unit tests
          command: cargo test --package shuttle-service --features="codegen,loader" --lib -- --nocapture
      - run:
          name: Run integration tests
          command: cargo test --package shuttle-service --features="codegen,loader" --test '*' -- --nocapture
      - save-cargo-cache
  platform-test:
    parameters:
      crate:
        description: "Crate to test"
        type: string
    # Using an image since tests will start a docker container
    executor: image-ubuntu
    steps:
      - install-rust
      - install-protoc
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore-cargo-cache
      - apply-patches
      - run:
          name: Run unit tests
          command: cargo test --package << parameters.crate >> --all-features --lib -- --nocapture
      - run:
          name: Run integration tests
          # Only run integration tests if there are any
          command: |
            set +o pipefail
            (cargo test --package << parameters.crate >> --all-features --test '*' -- --list 2>&1 | grep -q "no test target matches pattern") && echo "nothing to test" || cargo test --package << parameters.crate >> --all-features --test '*' -- --nocapture
      - save-cargo-cache
  e2e-test:
    resource_class: xlarge
    executor: image-ubuntu
    steps:
      - install-rust
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore-buildx-cache
      - run:
          name: Make images for tests
          command: |
            sudo mkdir -p $BUILDX_CACHE && sudo chown -R circleci:circleci $BUILDX_CACHE
            make images
      - save-buildx-cache
      - apply-patches
      - run:
          name: Run the E2E tests
          command: |
            # clean up a potential existing deployments before running
            # the tests just in case the environment is not clean
            make down
            BUILDX_CACHE=/tmp/cache/buildx make up

            SHUTTLE_TESTS_NETWORK=shuttle-dev_user-net SHUTTLE_TESTS_RUNTIME_IMAGE=public.ecr.aws/shuttle-dev/deployer:latest cargo test --package shuttle-gateway --all-features --lib -- --nocapture

            BUILDX_CACHE=/tmp/cache/buildx make test
      - save_cache:
          paths:
            - "/tmp/cache/buildx"
          key: docker-buildx-{{ .Branch }}
          when: always
  build-and-push:
    resource_class: xlarge
    executor: image-ubuntu
    steps:
      - checkout
      - restore-buildx-cache
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          public-registry: true
      - run:
          name: Make and push images
          command: |
            PUSH=true PLATFORMS=linux/amd64 make images
      - save-buildx-cache
  build-binaries-linux:
    machine:
      image: << parameters.image >>
    resource_class: << parameters.resource_class >>
    parameters:
      target:
        description: "Linux target to build for"
        type: string
      image:
        description: "Machine image to use"
        type: string
      resource_class:
        description: "The resource type to use for the machine"
        type: string
    steps:
      - checkout
      - run: sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt install -y libssl-dev musl-tools clang
      - run:
          name: Install Rust
          command: curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain 1.65.0 --target << parameters.target >>
      - run:
          name: Build
          command: |
            # From https://github.com/briansmith/ring/issues/1414#issuecomment-1055177218
            export CC_aarch64_unknown_linux_musl=clang
            # "vendored-openssl" is from https://github.com/cross-rs/cross/issues/229#issuecomment-597898074
            cargo build --release --package cargo-shuttle --features vendored-openssl --target << parameters.target >>
      - make-artifact:
          target: << parameters.target >>
  build-binaries-windows:
    executor:
      name: win/server-2022
      size: medium
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - checkout
      - run: choco install -y strawberryperl
      - run:
          name: Install Rust
          command: |
            wget -OutFile "C:\rustup-init.exe" https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
            C:\rustup-init.exe -y --default-toolchain 1.65.0 --target x86_64-pc-windows-msvc
      - run:
          name: Build
          command: |
            # From https://github.com/alexcrichton/openssl-src-rs/issues/45
            # Because of https://github.com/openssl/openssl/issues/9048
            $env:OPENSSL_SRC_PERL="C:\Strawberry\perl\bin\perl.exe"
            # "vendored-openssl" is from https://github.com/cross-rs/cross/issues/229#issuecomment-597898074
            ..\.cargo\bin\cargo.exe build --release --package cargo-shuttle --features vendored-openssl --target x86_64-pc-windows-msvc
      - make-artifact:
          target: x86_64-pc-windows-msvc
          suffix: ".exe"
  build-binaries-mac:
    macos:
      xcode: 12.5.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Rust
          command: curl --proto '=https' https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain 1.65.0 --target x86_64-apple-darwin
      - run:
          name: Build
          command: |
            # "vendored-openssl" is from https://github.com/cross-rs/cross/issues/229#issuecomment-597898074
            cargo build --release --package cargo-shuttle --features vendored-openssl --target x86_64-apple-darwin
      - make-artifact:
          target: x86_64-apple-darwin
  publish-github-release:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - attach_workspace:
          at: artifacts
      - run:
          name: "Set tag in environment"
          command: |
            cat artifacts/bash.env >> "$BASH_ENV"
            rm artifacts/bash.env
      - run:
          name: "Publish Release on GitHub"
          # Since each binary is in a sub directory named after its target, we flatten
          # the artifacts directory before passing it to ghr
          command: |
            find artifacts -mindepth 2 -type f -exec mv -t artifacts {} +
            go install github.com/tcnksm/ghr@v0.16.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -draft ${TAG} ./artifacts/

workflows:
  version: 2
  ci:
    jobs:
       - workspace-fmt
       - workspace-clippy:
           name: workspace-clippy-<< matrix.framework >>
           requires:
             - workspace-fmt
           matrix:
             parameters:
               framework: ["web-actix-web", "web-axum", "web-rocket", "web-poem", "web-thruster", "web-tide", "web-tower","web-warp", "web-salvo", "bot-serenity", "bot-poise"]
       - check-standalone:
           matrix:
             parameters:
               path:
                 - resources/aws-rds
                 - resources/persist
                 - resources/secrets
                 - resources/shared-db
                 - resources/static-folder
       - service-test:
           requires:
             - workspace-clippy
       - platform-test:
           requires:
             - workspace-clippy
           matrix:
             parameters:
               crate: ["shuttle-deployer", "cargo-shuttle", "shuttle-codegen", "shuttle-common", "shuttle-proto", "shuttle-provisioner", "shuttle-runtime"]
       - e2e-test:
           requires:
             - service-test
             - platform-test
             - check-standalone
           filters:
             branches:
               only: production
       - build-and-push:
           requires:
             - e2e-test
           filters:
             branches:
               only: production
       - build-binaries-linux:
           name: build-binaries-x86_64
           image: ubuntu-2204:2022.04.1
           target: x86_64-unknown-linux-musl
           resource_class: medium
           filters:
             branches:
               only: production
       - build-binaries-linux:
           name: build-binaries-aarch64
           image: ubuntu-2004:202101-01
           target: aarch64-unknown-linux-musl
           resource_class: arm.medium
           filters:
             branches:
               only: production
       - build-binaries-windows:
          filters:
            branches:
              only: production
       - build-binaries-mac:
          filters:
            branches:
             only: production
       - publish-github-release:
          requires:
            - build-binaries-x86_64
            - build-binaries-aarch64
            - build-binaries-windows
            - build-binaries-mac
          filters:
            branches:
             only: production
