version: 2.1

orbs: 
  docker-buildx: sensu/docker-buildx@1.1.1
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build-test-and-push:
    resource_class: xlarge
    machine:
      image: ubuntu-2204:2022.04.1
      docker_layer_caching: true
    steps:
      - checkout
      - docker-buildx/install:
          version: 0.8.2
          qemu-user-static-version: 7.0.0-7
      - restore_cache:
          keys:
            # Try lock cache first
            - docker-buildx-{{ checksum "./Cargo.lock" }}
            # Try branch cache next
            - docker-buildx-{{ .Branch }}
            # Fallback to main cache
            - docker-buildx-main
      - run:
          command: |
            export BUILDX_CACHE=/tmp/cache/buildx
            sudo mkdir -p $BUILDX_CACHE && sudo chown -R circleci:circleci $BUILDX_CACHE
            make images
      - save_cache:
          paths:
            - "/tmp/cache/buildx"
          key: docker-buildx-{{ checksum "./Cargo.lock" }}
          when: always
      - run:
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run:
          name: Run the E2E tests
          command: |
            mkdir -p ~/.cargo
            cat\<< EOF > ~/.cargo/config.toml
            [patch.crates-io]
            shuttle-service = { path = "$PWD/service" }
            EOF

            make down
            docker volume create shuttle-backend-vol
            docker volume create shuttle-cargo-registry-vol
            cd e2e; BUILDX_CACHE=/tmp/cache/buildx SHUTTLE_API_KEY=test-key cargo test -- --nocapture
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - aws-ecr/ecr-login:
                aws-access-key-id: AWS_ACCESS_KEY_ID
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY
                public-registry: true
            - run:
               command: |
                 make clean
                 PUSH=true BUILDX_CACHE=/tmp/cache/buildx PLATFORMS=linux/amd64,linux/arm64 make images
      - save_cache:
          paths:
            - "/tmp/cache/buildx"
          key: docker-buildx-{{ checksum "./Cargo.lock" }}
          when: always
      - save_cache:
          paths:
            - "/tmp/cache/buildx"
          key: docker-buildx-{{ .Branch }}
          when: always
workflows:
  version: 2
  build-test-and-push:
    jobs:
      - build-test-and-push
