[package]
name = "unveil-service"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the unveil platform"

[dependencies]
rocket = "0.5.0-rc.1"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"] }
thiserror = "1.0"
