[package]
name = "shuttle-service"
version = "0.2.5"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
libloading = { version = "0.7.3", optional = true }
sync_wrapper = { version = "0.1", optional = true }
axum = { version = "0.4", optional = true }
rocket = { version = "0.5.0-rc.1", optional = true }
sqlx = { version = "0.5", optional = true }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }
thiserror = "1.0"

shuttle-codegen = { version = "0.2.5", path = "../codegen", optional = true }

[dev-dependencies]
portpicker = "0.1.1"

[features]
default = ["codegen"]
codegen = ["shuttle-codegen"]
loader = ["libloading"]

sqlx-integration = ["sqlx/runtime-tokio-native-tls"]
sqlx-postgres = ["sqlx-integration", "sqlx/postgres"]

web-axum = ["axum", "sync_wrapper"]
web-rocket = ["rocket"]
