[package]
name = "shuttle-service"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.62"
async-trait = "0.1.57"
axum = { version = "0.5.15", optional = true }
bincode = { version = "1.2.1", optional = true }
cargo = { version = "0.64.0", optional = true }
cargo_metadata = "0.15.0"
chrono = "=0.4.22"
crossbeam-channel = "0.5.6"
futures = { version = "0.3.23", features = ["std"] }
hyper = { version = "0.14.20", features = ["server", "tcp", "http1"], optional = true }
libloading = { version = "0.7.3", optional = true }
pipe = "0.4.0"
poem = { version = "1.3.40", optional = true }
rocket = { version = "0.5.0-rc.2", optional = true }
salvo = { version = "0.34.3", optional = true }
serde_json = "1.0.83"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"], optional = true }
sync_wrapper = { version = "0.1.1", optional = true }
thiserror = "1.0.32"
tide = { version = "0.16.0", optional = true }
tokio = { version = "=1.20.1", features = ["rt", "rt-multi-thread", "sync"] }
tower = { version = "0.4.13", features = ["make"], optional = true }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
uuid = { version = "1.1.2", features = ["v4"] }

# Tide does not have tokio support. So make sure async-std is compatible with tokio
# https://github.com/http-rs/tide/issues/791
[dependencies.async-std]
version = "1.12.0"
optional = true
features = ["tokio1"]

[dependencies.shuttle-codegen]
version = "0.5.2"
path = "../codegen"
optional = true

[dev-dependencies]
portpicker = "0.1.1"
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "postgres"] }
tokio = { version = "1.20.1", features = ["macros"] }
uuid = { version = "1.1.2", features = ["v4"] }

[dependencies.shuttle-common]
version = "0.5.2"
default-features = false
path = "../common"

[features]
default = ["codegen"]
codegen = ["shuttle-codegen"]
loader = ["cargo", "libloading"]

web-axum = ["axum", "sync_wrapper"]
web-rocket = ["rocket"]
web-tide = ["tide", "async-std"]
web-tower = ["tower", "hyper"]
web-poem = ["poem"]
web-salvo = ["salvo"]

bot-serenity = ["serenity"]
