[package]
name = "shuttle-service"
version = "0.2.4"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
rocket = "0.5.0-rc.1"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls"] }
tokio = { version = "1.0", features = ["rt"] }
thiserror = "1.0"
