[package]
name = "shuttle-service"
version = "0.12.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
# TODO: debug the libgit2-sys conflict with cargo-edit when upgrading cargo to 0.66
cargo = { version = "0.65.0", optional = true }
cargo_metadata = { version = "0.15.2", optional = true }
crossbeam-channel = { version = "0.5.6", optional = true }
pipe = { version = "0.4.0", optional = true }
serde_json = { workspace = true, optional = true }
strfmt = "0.2.2"
thiserror = { workspace = true }
tokio = { version = "1.26.0", features = ["sync"], optional = true }
tracing = { workspace = true, optional = true }

[dependencies.shuttle-codegen]
workspace = true
optional = true

[dependencies.shuttle-common]
workspace = true
features = ["service"]

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt"] }

[features]
default = ["codegen"]

codegen = ["shuttle-codegen/frameworks"]
builder = ["cargo", "cargo_metadata", "crossbeam-channel", "pipe", "tokio", "tracing"]
