[package]
name = "shuttle-service"
version = "0.11.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
# TODO: debug the libgit2-sys conflict with cargo-edit when upgrading cargo to 0.66
cargo = { version = "0.65.0", optional = true }
cargo_metadata = "0.15.2"
crossbeam-channel = "0.5.6"
pipe = "0.4.0"
serde_json = { workspace = true }
strfmt = "0.2.2"
thiserror = { workspace = true }
tokio = { version = "1.26.0", features = ["sync"] }
tracing = { workspace = true }

[dependencies.shuttle-codegen]
workspace = true
optional = true

[dependencies.shuttle-common]
workspace = true
features = ["tracing", "service"]

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt"] }

[features]
default = ["codegen"]

codegen = ["shuttle-codegen/frameworks"]
builder = ["cargo"]
