[package]
name = "shuttle-service"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
axum = { version = "0.5.7", optional = true }
cargo = { version = "0.62.0", optional = true }
chrono = "0.4.19"
futures = { version = "0.3.21", features = ["std"] }
hyper = { version = "0.14.19", features = ["server", "tcp", "http1"], optional = true }
lazy_static = "1.4.0"
libloading = { version = "0.7.3", optional = true }
log = "0.4.17"
regex = "1.5.6"
rocket = { version = "0.5.0-rc.2", optional = true }
sqlx = { version = "0.5.13", optional = true }
sync_wrapper = { version = "0.1.1", optional = true }
thiserror = "1.0.31"
tide = { version = "0.16.0", optional = true }
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread"] }
tower = { version = "0.4.12", features = ["make"], optional = true }

[dependencies.shuttle-codegen]
version = "0.3.0"
path = "../codegen"
optional = true

[dependencies.shuttle-common]
version = "0.3.0"
path = "../common"

[dev-dependencies]
portpicker = "0.1.1"
uuid = "1.1.1"

[features]
default = ["codegen"]
codegen = ["shuttle-codegen"]
loader = ["cargo", "libloading"]

sqlx-integration = ["sqlx/runtime-tokio-native-tls"]
sqlx-postgres = ["sqlx-integration", "sqlx/postgres"]

secrets = ["sqlx-postgres"]

web-axum = ["axum", "sync_wrapper"]
web-rocket = ["rocket"]
web-tide = ["tide"]
web-tower = ["tower", "hyper"]
