[package]
name = "shuttle-service"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
cargo = { version = "0.59.0", optional = true }
chrono = "0.4"
libloading = { version = "0.7.3", optional = true }
log = "0.4"
sync_wrapper = { version = "0.1", optional = true }
axum = { version = "0.5", optional = true }
rocket = { version = "0.5.0-rc.1", optional = true }
tide = { version = "0.16.0", optional = true }
tower = { version = "0.4", features = ["make"], optional = true }
hyper = { version = "0.14", features = ["server", "tcp", "http1"], optional = true }
sqlx = { version = "0.5", optional = true }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }
thiserror = "1.0"
lazy_static = "1.4"
regex = "1.5"

shuttle-codegen = { version = "0.3.0", path = "../codegen", optional = true }
shuttle-common = { version = "0.3.0", path = "../common" }

[dev-dependencies]
portpicker = "0.1.1"
uuid = "0.8.2"

[features]
default = ["codegen"]
codegen = ["shuttle-codegen"]
loader = ["cargo", "libloading"]

sqlx-integration = ["sqlx/runtime-tokio-native-tls"]
sqlx-postgres = ["sqlx-integration", "sqlx/postgres"]

secrets = ["sqlx-postgres"]

web-axum = ["axum", "sync_wrapper"]
web-rocket = ["rocket"]
web-tide = ["tide"]
web-tower = ["tower", "hyper"]
