[package]
name = "shuttle-codegen"
version = "0.11.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Proc-macro code generator for the shuttle.rs service"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = { version = "1.0.104", features = ["full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
trybuild = "1.0.72"
