[package]
name = "shuttle-poise"
version = "0.36.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a poise discord bot on shuttle"
keywords = ["shuttle-service", "poise", "discord-bot", "serenity"]

[workspace]

[dependencies]
poise = "0.5.2"
shuttle-runtime = { path = "../../runtime", version = "<=0.40.0", default-features = false }
