[package]
name = "shuttle-poise"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a poise discord bot on shuttle"
keywords = ["shuttle-service", "poise", "discord-bot", "serenity"]

[dependencies]
poise = "0.5.5"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
shuttle-secrets = { path = "../../resources/secrets" }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
