[package]
name = "shuttle-tower"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a tower webserver on shuttle"
keywords = ["shuttle-service", "tower"]

[dependencies]
hyper = { workspace = true, features = ["server", "tcp", "http1"] }
tower = { workspace = true, features = ["make"] }

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
