[package]
name = "shuttle-axum"
version = "0.41.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run an axum webserver on shuttle"
keywords = ["shuttle-service", "axum"]

[workspace]

[dependencies]
axum = { version = "0.7.3", optional = true }
axum-0-6 = { package = "axum", version = "0.6.13", optional = true }
shuttle-runtime = { path = "../../runtime", version = "0.41.0", default-features = false }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["axum"]

axum-0-6 = ["dep:axum-0-6"]
