[package]
name = "shuttle-axum"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run an axum webserver on shuttle"
keywords = ["shuttle-service", "axum"]

[dependencies]
axum = "0.6.18"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
