[package]
name = "shuttle-axum"
version = "0.24.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run an axum webserver on shuttle"
keywords = ["shuttle-service", "axum"]

[workspace]

[dependencies]
axum = { version = "0.6.10" }
shuttle-runtime = { path = "../../runtime", version = "0.24.0" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
