[package]
name = "shuttle-turso"
version = "0.22.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to obtain a client connected to a Turso database"
keywords = ["shuttle-service", "turso"]

[dependencies]
async-trait = "0.1.56"
libsql-client = { version = "=0.30.1" }
serde = { version = "1.0.148", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.22.0", default-features = false }
url = { version = "2.3.1", features = ["serde"] }


[dev-dependencies]
tempfile = "3.3.0"
tokio = "1.28.2"
