[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
portpicker = "0.1.1"
colored = "2"
rand = "0.8"
