[package]
name = "shuttle-poem"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a poem webserver on shuttle"
keywords = ["shuttle-service", "poem"]

[dependencies]
poem = "1.3.56"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
