[package]
name = "shuttle-rocket"
version = "0.12.0-rc1"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a rocket webserver on shuttle"
keywords = ["shuttle-service", "rocket"]

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2" }
shuttle-runtime = { path = "../../runtime", version = "0.12.0-rc1" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
