[package]
name = "shuttle-rocket"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a rocket webserver on shuttle"
keywords = ["shuttle-service", "rocket"]

[dependencies]
rocket = "0.5.0-rc.3"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
