[package]
name = "shuttle-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
opentelemetry-proto = { version = "0.2.0", features = ["gen-tonic", "logs"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default"] }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "tonic"]
