[package]
name = "shuttle-static-folder"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Plugin to get a static folder at runtime on shuttle"
keywords = ["shuttle-service", "static-folder"]

[dependencies]
async-trait = { workspace = true }
dunce = { workspace = true }
fs_extra = "1.3.0"
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[dependencies.shuttle-service]
workspace = true
default-features = false

[dev-dependencies]
tempfile = "3.3.0"
tokio = { version = "1.22.0", features = ["macros", "rt"] }
