[package]
name = "shuttle-static-folder"
version = "0.7.3"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to get a static folder at runtime on shuttle"
keywords = ["shuttle-service", "static-folder"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
shuttle-service = { path = "../../service", version = "0.7.2", default-features = false }
tokio = { version = "1.19.2", features = ["rt"] }

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.19.2", features = ["macros"] }
