[package]
name = "shuttle-static-folder"
version = "0.12.0-rc1"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to get a static folder at runtime on shuttle"
keywords = ["shuttle-service", "static-folder"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
fs_extra = "1.3.0"
shuttle-service = { path = "../../service", version = "0.12.0-rc1", default-features = false }
tracing = "0.1.37"

[dev-dependencies]
tempfile = "3.3.0"
tokio = { version = "1.19.2", features = ["macros", "rt"] }
