[package]
name = "shuttle-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "4.0.0", features = [ "derive", "env" ] }
dirs = "4.0.0"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
toml = "0.5.9"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dependencies.shuttle-common]
version = "0.7.2"
path = "../common"
