[package]
name = "shuttle-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.2"
prost-types = "0.11.0"
tonic = "0.8.3"

[dependencies.shuttle-common]
workspace = true
features = ["models"]

[build-dependencies]
tonic-build = "0.8.3"
