[package]
name = "shuttle-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Library for all the gRPC definitions used by shuttle"

[dependencies]
shuttle-common = { workspace = true, features = [
    "claims",
    "service",
    "wasm",
    "models",
    "backend",
] }

anyhow = { workspace = true }
chrono = { workspace = true }
dunce = { workspace = true }
home = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tonic-build = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
