[package]
name = "shuttle-proto"
version = "0.5.1"
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.0"
tonic = "0.8.0"

[dependencies.shuttle-common]
version = "0.5.1"
path = "../common"

[build-dependencies]
tonic-build = "0.8.0"
