[package]
name = "shuttle-actix-web"
version = "0.1.0"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
actix-web = { version = "4.3.1" }
shuttle-runtime = { path = "../../runtime", version = "0.1.0" }
num_cpus = "1.15.0"
