[package]
name = "shuttle-persist"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Plugin for persist objects"
keywords = ["shuttle-service", "persistence"]

[dependencies]
async-trait = { workspace = true }
bincode = "1.2.1"
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dependencies.shuttle-common]
workspace = true

[dependencies.shuttle-service]
workspace = true
default-features = false
