[package]
name = "shuttle-shared-db"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
shuttle-service = { path = "../../service", default-features = false }
sqlx = { version = "0.5.13", features = ["runtime-tokio-native-tls", "postgres"] }
tokio = { version = "1.19.2", features = ["rt"] }
