[package]
name = "shuttle-common"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Common library for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true, optional = true }
async-trait = { workspace = true , optional = true }
axum = { workspace = true, optional = true }
chrono = { workspace = true, features = ["serde"] }
comfy-table = { version = "6.1.3", optional = true }
crossterm =  { version = "0.25.0", optional = true }
http = { version = "0.2.8", optional = true }
once_cell = { workspace = true }
reqwest = { version = "0.11.13", optional = true }
rustrict = "0.5.5"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
strum = { version = "0.24.1", features = ["derive"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }

[features]
backend = ["async-trait", "axum"]
display = ["comfy-table", "crossterm"]
models = ["anyhow", "async-trait", "display", "http", "reqwest", "serde_json"]
