[package]
name = "shuttle-common"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "Common library for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0.62", optional = true}
chrono = { version = "0.4.22", features = ["serde"] }
comfy-table = { version = "6.1.0", optional = true }
crossterm =  { version = "0.25.0", optional = true }
once_cell = "1.13.1"
rocket = "0.5.0-rc.2"
rustrict = "0.5.0"
serde = "1.0.137"
serde_json = "1.0.83"
strum = { version = "0.24.1", features = ["derive"] }
tracing = "0.1.36"
uuid = { version = "1.1.1", features = ["v4", "serde"] }

[features]
default = []
full = ["anyhow", "crossterm", "comfy-table"]
