[package]
name = "shuttle-common"
version = "0.7.3"
edition.workspace = true
licence.workspace = true
description = "Common library for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true, optional = true }
async-trait = { version = "0.1.58", optional = true }
axum = { version = "0.6.0", optional = true }
chrono = { version = "0.4.23", features = ["serde"] }
comfy-table = { version = "6.1.3", optional = true }
crossterm =  { version = "0.25.0", optional = true }
http = { version = "0.2.8", optional = true }
once_cell = { workspace = true }
reqwest = { version = "0.11.13", optional = true }
rustrict = "0.5.5"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = { version = "1.0.89", optional = true }
strum = { version = "0.24.1", features = ["derive"] }
tracing = { workspace = true }
uuid = { version = "1.2.2", features = ["v4", "serde"] }

[features]
default = ["models"]

backend = ["async-trait", "axum"]
display = ["comfy-table", "crossterm"]
models = ["anyhow", "async-trait", "display", "http", "reqwest", "serde_json"]
