[package]
name = "shuttle-common"
version = "0.7.2"
edition = "2021"
license = "Apache-2.0"
description = "Common library for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.62", optional = true }
async-trait = { version = "0.1.52", optional = true }
chrono = { version = "0.4.22", features = ["serde"] }
comfy-table = { version = "6.1.0", optional = true }
crossterm =  { version = "0.25.0", optional = true }
http = { version = "0.2.8", optional = true }
once_cell = "1.13.1"
reqwest = { version = "0.11.11", optional = true }
rustrict = "0.5.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.85", optional = true }
strum = { version = "0.24.1", features = ["derive"] }
tracing = "0.1.36"
uuid = { version = "1.1.1", features = ["v4", "serde"] }

[features]
default = ["models"]

display = ["comfy-table", "crossterm"]
models = ["anyhow", "async-trait", "display", "http", "reqwest", "serde_json"]
