[package]
name = "shuttle-common"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
description = "Common library for the shuttle platform (https://www.shuttle.rs/)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.137"
serde_json = "1.0.81"
uuid = { version = "1.1.1", features = ["v4", "serde"] }
rocket = "0.5.0-rc.2"
anyhow = "1.0.57"
lazy_static = "1.4.0"
log = { version = "0.4.17", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
