[package]
name = "shuttle-sqlite"
version = "0.22.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
indexmap = { version = "1.9.3", features = ["serde"] }
regex = "1.8.3"
serde = "1.0.163"
shuttle-service = { version = "0.22.0", path = "../../service" }
sqlx = { version = "0.6.3", features = ["sqlite", "runtime-tokio-rustls"] }
thiserror = "1.0.40"
tracing = "0.1.37"

[dev-dependencies]
pretty_assertions = "1.4.0"
serde_json = "1.0.96"
