[package]
name = "secrets"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.62"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
shuttle-service = { version = "0.5.0", features = ["secrets", "web-rocket"] }
