[package]
name = "postgres"
version = "0.1.0"
edition = "2021"
description = "Shuttle test project"
license = "Apache 2.0"
homepage = "https://www.shuttle.rs/"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1.0"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"] }
shuttle-service = "0.2"
