[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1.0"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"] }
shuttle-service = { version = "0.4.0", features = ["web-rocket"] }
shuttle-shared-db = { version = "0.4.0", features = ["postgres"] }
shuttle-secrets = "0.4.0"
