[package]
name = "shuttle-secrets"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Plugin to for managing secrets on shuttle"
keywords = ["shuttle-service", "secrets"]

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dependencies.shuttle-service]
workspace = true
default-features = false
