[package]
name = "shuttle-secrets"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to for managing secrets on shuttle"
keywords = ["shuttle-service", "secrets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
lazy_static = "1.4.0"
regex = "1.5.6"
shuttle-service = { path = "../../service", version = "0.5.2", default-features = false }
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "postgres"] }
