[package]
name = "shuttle-shared-db"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to for managing shared databases on shuttle"
keywords = ["shuttle-service", "database"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
shuttle-service = { path = "../../service", default-features = false }
sqlx = { version = "0.5.13", features = ["runtime-tokio-native-tls"] }
tokio = { version = "1.19.2", features = ["rt"] }

[features]
postgres = ["sqlx/postgres"]
