[package]
name = "shuttle-shared-db"
version = "0.12.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin for managing shared databases on shuttle"
keywords = ["shuttle-service", "database"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
mongodb = { version = "2.3.0", optional = true }
shuttle-service = { path = "../../service", version = "0.12.0", default-features = false }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls"], optional = true }

[features]
postgres = ["sqlx/postgres"]
