[package]
name = "shuttle-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
async-recursion = { version = "1.0.4" }
async-trait = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
flate2 = { workspace = true }
nbuild-core = "0.1.2"
oci-spec = { version = "0.5.7" }
regex = { version = "1.5.6" }
sha2 = { version = "0.10.2" }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "io-util", "process", "rt-multi-thread"] }
tokio-stream = { version = "0.1.14" }
tokio-tar = { version = "0.3.0" }
toml = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default"] }
ulid = { workspace = true }
url = { workspace = true }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "tonic"]

[dependencies.shuttle-proto]
workspace = true

[dev-dependencies]
hex = "0.4.3"
portpicker = { workspace = true }
pretty_assertions = { workspace = true }
shuttle-common-tests = { workspace = true }
