[package]
name = "deployer"
version = "0.1.0"
edition = "2021"
description = "Service with instances created per project for handling the compliation, loading, and execution of Shuttle services"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
http = "0.2.8"
anyhow = "1.0.57"
lazy_static = "1.4.0"
regex = "1.5.6"
futures = "0.3.7"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
sqlx = { version = "0.5.13", features = ["runtime-tokio-native-tls", "sqlite"] }
tower = { version = "0.4.12", features = ["make"] }
axum = "0.5.7"
bytes = "1.1.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
