[package]
name = "shuttle-deployer"
version = "0.16.0"
edition.workspace = true
license.workspace = true
description = "Service to execute the deployment of projects on shuttle"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
http = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies.shuttle-common]
workspace = true
features = ["backend"]
