#cloud-config

# Install needed packages
packages:
  - docker.io
  - nfs-common

# Create the docker group
groups:
  - docker

# Add default auto-created user to docker group
system_info:
  default_user:
    groups: [docker]

# Create our systemd files
write_files:
  - encoding: b64
    content: ${opt_shuttle_content}
    path: /lib/systemd/system/opt-shuttle.mount
    owner: root:root
    permissions: "0644"
  - encoding: b64
    content: ${shuttle_backend_content}
    path: /lib/systemd/system/shuttle-backend.service
    owner: root:root
    permissions: "0644"

# Up services on every boot
bootcmd:
  - [systemctl, start, "opt-shuttle.mount"]
  - [systemctl, start, "shuttle-backend.service"]
