[package]
name = "shuttle-axum"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
shuttle-next = "0.8.0"
tracing = "0.1.37"

[dev-dependencies]
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
hyper = "0.14.23"
