[package]
name = "shuttle-serenity"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a serenity server on shuttle"
keywords = ["shuttle-service", "serenity"]

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
anyhow = { workspace = true }
shuttle-secrets = { path = "../../resources/secrets" }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
