[package]
name = "shuttle-warp"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a warp webserver on shuttle"
keywords = ["shuttle-service", "warp"]

[dependencies]
warp = "0.3.5"

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
