[package]
name = "shuttle-warp"
version = "0.12.0-rc1"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = { version = "0.3.3" }
shuttle-runtime = { path = "../../runtime", version = "0.12.0-rc1" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
