[package]
name = "shuttle-provisioner"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Service responsible for provisioning and managing resources for services"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.51.0"
aws-sdk-rds = "0.21.0"
clap = { workspace = true, features = ["env"] }
fqdn = "0.2.3"
mongodb = "2.3.1"
prost = "0.11.2"
rand = { workspace = true }
sqlx = { version = "0.6.2", features = [
  "postgres",
  "runtime-tokio-native-tls",
] }
thiserror = { workspace = true }
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.3"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies.shuttle-proto]
workspace = true

[dev-dependencies]
ctor = "0.1.26"
once_cell = { workspace = true }
portpicker = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
tonic-build = "0.8.3"
