[package]
name = "provisioner"
version = "0.1.0"
edition = "2021"
description = "Service responsible for provisioning and managing resources for services"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive", "env"] }
prost = "0.10"
rand = "0.8.5"
sqlx = { version = "0.5", features = ["postgres", "runtime-tokio-native-tls"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"

proto = { path = "../proto" }

[dev-dependencies]
ctor = "0.1"
lazy_static = "1.4"
portpicker = "0.1"

[build-dependencies]
tonic-build = "0.7"
