[package]
name = "shuttle-common-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hyper = { workspace = true }
shuttle-common = { workspace = true }
tower = { workspace = true }
cargo-shuttle = { path = "../cargo-shuttle" }
portpicker = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
reqwest = { workspace = true }
tokio-stream = { workspace = true }

[dependencies.shuttle-proto]
workspace = true
