[package]
name = "shuttle-elasticache"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to provision AWS Elasticache"
keywords = ["shuttle-service", "elasticache"]

[dependencies]
shuttle-service = { path = "../../service", version = "0.8.0", default-features = false }
redis = "0.22.3"
