[package]
name = "shuttle-thruster"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a thruster webserver on shuttle"
keywords = ["shuttle-service", "thruster"]

[dependencies]
thruster = { version = "1.3.0" }

[dependencies.shuttle-runtime]
workspace = true

[dev-dependencies]
thruster = { version = "1.3.0", features = ["hyper_server"] }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
