[package]
name = "shuttle-tide"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service implementation to run a tide webserver on shuttle"
keywords = ["shuttle-service", "tide"]

[dependencies]
tide = "0.16.0"

[dependencies.shuttle-runtime]
workspace = true

# Tide does not have tokio support. So make sure async-std is compatible with tokio
# https://github.com/http-rs/tide/issues/791
[dependencies.async-std]
version = "1.12.0"
features = ["tokio1"]

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
