[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["uuid", "serde_json", "json"] }
cargo = "0.59.0"
anyhow = "1.0.54"
uuid = { version = "0.8.2", features = ["v4"] }
async-mutex = "1.4.0"
serde = "1.0.136"
flurry = "0.3.1"