name: CI
on:
  push:
    tags:
      - 'v*'

jobs:
  Build-And-Deploy:
    runs-on: self-hosted
    env:
      CONTAINER_REGISTRY: public.ecr.aws/shuttle
    steps:
    - uses: shuttle-hq/checkout@v2
    - name: Configure AWS Credentials
      uses: shuttle-hq/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Docker Login
      run: |
        aws ecr-public get-login-password | docker login --username AWS --password-stdin $CONTAINER_REGISTRY
    - name: Build And Push Backend Image
      uses: shuttle-hq/build-push-action@v2
      with:
        context: .
        file: {context}/api/Containerfile
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/backend:${{ github.sha }},${{ env.CONTAINER_REGISTRY }}/backend:latest
    - name: Build And Push Provisioner Image
      uses: shuttle-hq/build-push-action@v2
      with:
        context: .
        file: {context}/provisioner/Containerfile
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/provisioner:${{ github.sha }},${{ env.CONTAINER_REGISTRY }}/provisioner:latest
    - name: Deploy Image
      run: |
        ssh ubuntu@prod sudo systemctl restart shuttle-backend.service
        
