name: images
on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: public.ecr.aws/shuttle
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/setup-buildx-action@v2
    - name: Docker Login
      run: |
        aws ecr-public get-login-password |\
        docker login --username AWS --password-stdin $CONTAINER_REGISTRY
    - name: Build And Push Images
      run: |
        do_tags() {
            COMMIT=$(git rev-parse --short "$GITHUB_SHA")
            TAGS="$CONTAINER_REGISTRY/$1:$COMMIT"
            REF=${GITHUB_REF#refs/heads/}
            case "$REF" in
                "main")
                    TAGS="$CONTAINER_REGISTRY/$1:dev,$TAGS"
                    ;;
                v*)
                TAGS="$CONTAINER_REGISTRY/$1:latest,$CONTAINER_REGISTRY/$1:${REF},$TAGS"
                ;;
            esac
            echo $TAGS
        }

        docker buildx bake \
               -f docker-bake.hcl \
               --set provisioner.tags=$(do_tags provisioner) \
               --set provisioner.platform=linux/arm64,linux/amd64 \
               --set api.tags=$(do_tags backend) \
               --set api.platform=linux/arm64,linux/amd64 \
               --push provisioner api
        
