name: cargo-fmt

on:
  pull_request:
    branches: [main]
    paths: ["**/*.rs"]

  workflow_dispatch:

jobs:
  fmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check
  cargo_sort_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo install cargo-sort
      - run: cargo sort --check --workspace
  clippy_test:
    strategy:
      fail-fast: true
      matrix:
        features: ["web-axum", "web-rocket", "web-tide", "web-tower", web-poem]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run test with ${{ matrix.features}}
        run: |
          cargo clippy --tests \
                       --all-targets \
                       --features="codegen,loader,sqlx-integration,sqlx-postgres,secrets,${{ matrix.features }}" \
                       --no-deps -- \
                       --D warnings \
                       -A clippy::let-unit-value \
                       -A clippy::format-push-string
