name: cargo-test

on:
  push:
    branches: [main]
    paths: ["**/*.rs"]
  pull_request:
    branches: [main]
    paths: ["**/*.rs"]

  workflow_dispatch:

jobs:
  cargo_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: cargo build
      - run: cargo test
