name: cargo-test

on:
  push:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]
  pull_request:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo_test:
    runs-on: self-hosted
    steps:
      - uses: shuttle-hq/checkout@v2
      - uses: shuttle-hq/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: SHUTTLE_API_KEY=test-key cargo test -- --nocapture
