name: cargo-test

on:
  push:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]
  pull_request:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    strategy:
      fail-fast: true
      matrix:
        crate: ["shuttle-provisioner", "shuttle-api", "shuttle-service", "cargo-shuttle"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true      
      - name: cargo test ${{ matrix.crate }} --all-features
        run: cargo test --package ${{ matrix.crate }} --all-features
  e2e_tests:
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:
      - uses: shuttle-hq/checkout@v2
      - uses: shuttle-hq/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: e2e tests
        working-directory: ./e2e
        run: SHUTTLE_API_KEY=test-key cargo test -- --nocapture
