name: website

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/www.yml'
      - 'www/**'

env:
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  AUTH0_BASE_URL: https://www.shuttle.rs
  AUTH0_ISSUER_BASE_URL: https://shuttle-prod.eu.auth0.com
  AUTH0_CLIENT_ID: X77iwzR3Qm60kSIxxDEUVKOMFIQcDodp
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  SHUTTLE_API_BASE_URL: https://api.shuttle.rs

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: getsynth/checkout@v2
      - uses: getsynth/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: --prod
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_WWW_PROJECT_ID }}
          working-directory: ./www
          scope: ${{ secrets.VERCEL_ORG_ID }}
