[package]
name = "shuttle-resource-recorder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default"] }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "models"]
